Client goal-script
Qwiri/InnoDays2022 pull request #2
Opened 2022-04-25 15:16 UTC by memeToasty

pls review 🥰👉👈

2022-04-25 15:32 UTC, TomRomeo commented on client/goals.py
> +    url = f"http://{BACKEND_URL}/e/tor/{KICKER_ID}/{goal_id}"
add protocol to `BACKEND_URL`

2022-04-25 15:40 UTC, TomRomeo requested changes

2022-04-25 15:40 UTC, TomRomeo commented on client/goals.py
> +    continue
move this to 

```python
if __name__ == "__main__":
    # ...
```

2022-04-26 12:19 UTC, darmiel requested changes

2022-04-26 12:19 UTC, darmiel commented on client/goals.py
> +                    default='https://localhost', help='URL of Pinguin-backend')
make the default `http://localhost `

2022-04-26 12:19 UTC, darmiel commented on README.md
> +  -backend-url BACKEND_URL
```suggestion
  --backend-url BACKEND_URL
```

2022-04-26 12:19 UTC, darmiel commented on client/goals.py
> +parser.add_argument('-backend-url', type=str,
```suggestion
parser.add_argument('--backend-url', type=str,
```

2022-04-26 12:29 UTC, darmiel requested changes

2022-04-26 12:29 UTC, darmiel commented on client/goals.py
> +GOAL_TWO_ID = 1
```suggestion
GOAL_BLACK_ID = 1
GOAL_WHITE_ID = 2
```

2022-04-26 12:29 UTC, darmiel commented on client/goals.py
> +GOAL_TWO_PIN = 12
```suggestion
GOAL_BLACK_ID = 10 # ?
GOAL_WHITE_ID = 12 # ?
```

2022-04-26 12:29 UTC, darmiel commented on client/goals.py
> +        goal_id = GOAL_TWO_ID
```suggestion
    if channel == GOAL_BLACK_PIN:
        goal_id = GOAL_WHITE_ID
    else:
        goal_id = GOAL_BLACK_ID
```

2022-04-26 13:07 UTC, TomRomeo commented on README.md
> +usage: goals.py [-h] [--backend-url BACKEND_URL] [-kid KID]
```suggestion
usage: goals.py [-h] [--backend-url BACKEND_URL] [--kid KID]
```

2022-04-26 13:12 UTC, darmiel requested changes

2022-04-26 13:12 UTC, darmiel commented on client/goals.py
> +                    default='http://localhost', help='URL of Pinguin-backend')
```suggestion
                    default='http://localhost', help='URL of Penguin')
```

2022-04-26 13:13 UTC, darmiel approved these changes

2022-04-26 13:15 UTC, merged